apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth         
  namespace: kube-system  
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::547641599748:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-Rc2Uec9Jn7PD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters  
      rolearn: arn:aws:iam::547641599748:role/UdacityFlaskDeployCBKubectlRole 
      username: build   